### ISSUE TITLE
쿼리 파라미터 로그 남기기 (외부 라이브러리)

### ISSUE THREAD

**Issue by seongjihye1994** [seongjihye1994/spring-data-jpa#3]
# 쿼리 파라미터 로그 남기기 (외부 라이브러리)

### 쿼리 파라미터 로그 남기는 방법

1. 설정 파일에 추가하기
    
    ```yaml
    logging.level:
      org.hibernate.SQL: debug # JPA 실행 쿼리를 로그 파일에 남긴다.
      org.hibernate.type: trace # 파라미터까지 남긴다.
    ```
    

1. 외부 라이브러리 사용하기

build.gradle

```java
plugins {
	id 'org.springframework.boot' version '2.7.1'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
}

group = 'study'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	**implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.7' // SQL 실행 파라미터를 로그로 남기는 외부 라이브러리**
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

p6spy 외부 라이브러리를 사용해서 로그를 남길수도 있다.

쿼리 파라미터를 로그로 남기는 외부 라이브러리는 시스템 자원을 사용하므로, 

개발 단계에서는 편하게 사용해도 된다. 

하지만 운영시스템에 적용하려면 꼭 성능테스트를 하고 사용하는 것이 좋다.
